version: '3'
services:
    app:
        build: .
        volumes:
            - .:/app
        command: bash -c "composer install && ./vendor/bin/phpunit --coverage-text && echo 'Application is up! You can run commands :) ' && tail -f /dev/null"
